---
title: "lab9"
author: "Jiawen"
date: "2022-10-26"
output: 
       github_document: 
             html_preview: false
       html_document: default
       pdf_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos=c(CRAN="http://cran.rstudio.com"))
```

```{r}
install.packages("microbenchmark")
library(microbenchmark)
```

#PROBLEM 2create a n x k matrix 
```{R}
fun1 <- function(n = 100, k = 4, lambda = 4) {
  x <- NULL
  
  for (i in 1:n)
    x <- rbind(x, rpois(k, lambda)) #rpois: retern random numbers from pois, k means how many numbers should be returned; rbind,r menas rows, bind menas put them together; lambda means the mean 
  
  return(x)
}
f1 <- fun1(1000,4)
mean(f1)

fun1alt <- function(n = 100, k = 4, lambda = 4) {
  # YOUR CODE HERE
  x <- matrix( rpois(n*k, lambda), ncol=4)
  return(x)
}
f1 <- fun1alt(5000,4)
# Benchmarking
microbenchmark::microbenchmark(
  fun1(),
  fun1alt()
)

```
#way of creating matrix 
```{r}
d <- matrix(1:16,ncol=4)
d
```

```{r}
diag(d) #take diag elements
d[2]
d[2,1]
d[c(1,6,11,16)]
cbind(1:4,1:4)
d[cbind(1:4,1:4)]
```

#Problem 3: Find the column max (hint: Checkout the function max.col()).
```{r}
# Data Generating Process (10 x 10,000 matrix)
set.seed(1234)
M <- matrix(runif(12), ncol=4) #run random numbers from uniform distribution 
M

# Find each column's max value, 2 means column/1 means row, max means return the maximum number
fun2 <- function(x) {
  apply(x, 2, max)
}
fun2(M)

fun2alt <- function(x) {
  # YOUR CODE HERE, t(x) means flip matrix
  idx <- max.col(t(x))  #return the location
  x[cbind(idx,1:4)] #go back to the x matrix and return the value of location
  }
fun2alt(M)
x <- matrix(rnorm(1e4), nrow=10) #run random numbers from normal distribution 1e4=10000
# Benchmarking
microbenchmark::microbenchmark(
  fun2(x),
  fun2alt(x)
)
```

```{r}
# Bootstrap of an OLS
my_stat <- function(d) coef(lm(y ~ x, data=d)) #return coef from the regression 

# DATA SIM
set.seed(1)
n <- 500; R <- 1e4 #n is the sample size, R is tne number of resamplingwe do

x <- cbind(rnorm(n)); y <- x*5 + rnorm(n) #y is the output of regression, rnorm(n) is noise 

```
#problem 4
```{r}
library(parallel)
my_boot <- function(dat, stat, R, ncpus = 1L) {
  
  # Getting the random indices
  n <- nrow(dat)
  idx <- matrix(sample.int(n, n*R, TRUE), nrow=n, ncol=R)
 
  # Making the cluster using `ncpus`
  # STEP 1: GOES HERE
  # 1. CREATING A CLUSTER
library(parallel)
cl <- makePSOCKcluster(4)    
# 2. PREPARING THE CLUSTER
clusterSetRNGStream(cl, 123) # Equivalent to `set.seed(123)`

# 3. DO YOUR CALL
  # STEP 2: GOES HERE
clusterExport(cl,c("stat", "dat", "idx"), envir = environment())
    # STEP 3: THIS FUNCTION NEEDS TO BE REPLACES WITH parLapply
  ans <- parLapply(cl, seq_len(R), function(i) {
    stat(dat[idx[,i], , drop=FALSE])
  })
  # Coercing the list into a matrix
  ans <- do.call(rbind, ans)
  
  # STEP 4: GOES HERE
  
  ans
  
}
# Checking if we get something similar as lm
ans0 <- confint(lm(y~x)) #regress confidence interval 
ans1 <- my_boot(dat = data.frame(x, y), my_stat, R = R, ncpus = 2L)

# You should get something like this
t(apply(ans1, 2, quantile, c(.025,.975)))

ans0

```



#problem 4: 
```{r}
library(parallel)
R
```