library(data.table)
library(dtplyr)
library(dplyr)
library(ggplot2)

```{r}
met_url <- "https://github.com/USCbiostats/data-science-data/raw/master/02_met/met_all.gz"
```

```{r}
tmp <- "met.gz"
 if (!file.exists(tmp)) {
  download.file(
    url      = met_url,
    destfile = tmp,
        # method   = "libcurl", timeout = 1000 (you may need this option)
  )
}
```

```{r}
dat <- fread(tmp)
head(dat)
```

```{r}
data(USArrests)
USArrests_dt <- data.table(USArrests)
USArrests_dt[, plot(Murder, UrbanPop)]
```

```{r}
dat <- fread(tmp)
head(dat)
```

```{r}
# Creating a lazy table object
dat_ldt <- lazy_dt(dat, immutable = FALSE)
# We can use the address() function from data.table
address(dat)
address(dat_ldt$parent)
```

```{r}
dat[, list(USAFID, lat, lon)]
```

```{r}
dat_ldt %>% select(USAFID, lat, lon)
```

```{r}
dat[:,["USAFID", "lat", "lon"]]
```

```{r}
# Data.table
dat <- dat[,
  .(USAFID, WBAN, year, month, day, hour, min, lat, lon, elev,
    wind.sp, temp, atm.press)]
# Need to redo the lazy table
dat_ldt <- lazy_dt(dat)
```

```{r}
myxor <- function(x, y) {
  res <- logical(length(x))
  for (i in 1:length(x)) { #for is the loop
    res[i] <- # do something with x[i] and y[i], missing 
  }
  return(res)
}
```

```{r}
library(dplyr)
def myxor(x,y):
    return np.logical_or(
        np.logical_and(x, np.logical_not(y)),
        np.logical_and(np.logical_not(x), y)
    )
ans['myxor'] = myxor(x,y)
pa.DataFrame(ans)
```

```{r}
dat[(day == 1) & (lat > 40) & ((elev < 500) | (elev > 1000))] %>%
  nrow()
```

```{r}
ls()
```

```{r}
library(tidyverse)
dat[(temp>18) & (temp <25)] &>& nrow()
dat[is.na(temp)]
sample.int(100.10, replace = FALSE)
temp_isna[  sample.int(.N,10)]
dat[ !is.na(temp)] %>%
  sample.int(,.N,10)
```

```{r}
#0, 1, 1, 0, 0, 1 logical 

#Diabetes type 1, Diabetes type 2, Diabetes type 1, Diabetes type 2 logical variable to define it

#on, off, off, on, on, on

#5, 10, 1, 15, 0, 0, 1 integer

#1.0, 2.0, 10.0, 6.0 integer

#high, low, medium, medium, high  ?

#-1, 1, -1, -1, 1, logical

#.2, 1.5, .8, double
#π,π, exp 1, π,π double
```

```{r}
in_names  <- c("wind.sp", "temp", "atm.press")
out_names <- paste0(in_names, "_scaled") #The names of count columns in the output.
dat[,
    c(out_names) := lapply(.SD, function(x) x/sd(x, na.rm = TRUE)), #apply function to the list 
    .SDcols = in_names
    ]
# Looking at the first 6
head(dat[, .SD, .SDcols = out_names], n = 4) #.SD is outname
```

```{r}
as.list(USArrests)
lapply(USArrests,min)
```

```{r}
stations <- fread("ftp://ftp.ncdc.noaa.gov/pub/data/noaa/isd-history.csv")
stations[, USAF := as.integer(USAF)] #turn the varaibles into integer
# Dealing with NAs and 999999
stations[, USAF   := fifelse(USAF == 999999, NA_integer_, USAF)]
stations[, CTRY   := fifelse(CTRY == "", NA_character_, CTRY)]
stations[, STATE  := fifelse(STATE == "", NA_character_, STATE)]
# Selecting the three relevant columns, and keeping unique records
stations <- unique(stations[, list(USAF, CTRY, STATE)])
# Dropping NAs
stations <- stations[!is.na(USAF)]
head(stations, n = 4)
```

```{r}
 #something only in y that we will ignore them
stations[, n := 1:.N, by = .(USAF)] #by = .(USAF) go up by USAF
stations <- stations[n == 1,][, n := NULL] #= if the first ?  n := NULL delate from the matrix
```

```{r}
 dat[, temp_imp := fcoalesce(temp, mean(temp, na.rm = TRUE)), 
    by = .(STATE, year, month, day)
```

```{}
plotdata <-dat[USAFID == 720172][order(year, month, day)]
plotdata <- rbind(
  plotdata[, .(temp = temp, type = "raw")], #raw
  plotdata[USAFID == 720172][, .(temp = temp_imp, type = "filled")]
)
```